### ISSUE TITLE
Waiting a while after sound stopped gives error

### ISSUE THREAD

**Issue by ShaHar91** [Orfium/RxMusicPlayer-android#3]
Hi, first of all, nice work!!

I found a bug when music has finished playing, if you then wait a while the broadcastReceiver crashes with following error:

`2019-03-30 23:47:04.488 19052-19052/com.app.music.player E/ActivityThread: Service com.orfium.rx.musicplayer.media.MediaService has leaked IntentReceiver com.orfium.rx.musicplayer.playback.BasePlayback$audioNoisyReceiver$1@dfe2c57 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.orfium.rx.musicplayer.media.MediaService has leaked IntentReceiver com.orfium.rx.musicplayer.playback.BasePlayback$audioNoisyReceiver$1@dfe2c57 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1538)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1277)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1555)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1528)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1516)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:636)
        at com.orfium.rx.musicplayer.playback.BasePlayback.registerNoiseReceiver(BasePlayback.kt:107)
        at com.orfium.rx.musicplayer.playback.BasePlayback.play(BasePlayback.kt:42)
        at com.orfium.rx.musicplayer.media.MediaManager.play(MediaManager.kt:124)
        at com.orfium.rx.musicplayer.media.MediaManager.handlePlayRequest(MediaManager.kt:78)
        at com.orfium.rx.musicplayer.media.MediaManager.access$handlePlayRequest(MediaManager.kt:13)
        at com.orfium.rx.musicplayer.media.MediaManager$subscribeQueue$state$1.accept(MediaManager.kt:53)
        at com.orfium.rx.musicplayer.media.MediaManager$subscribeQueue$state$1.accept(MediaManager.kt:13)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.orfium.rx.musicplayer.common.ExtensionsKt.playStop(Extensions.kt:14)
        at com.app.music.player.PopularAdapter$PopularViewHolder$bind$1.onClick(PopularAdapter.kt:41)
        at android.view.View.performClick(View.java:7333)
        at android.view.View.performClickInternal(View.java:7299)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27772)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`

Also, the notification won't update if the music ended. The pause button stays in front and won't seem to toggle, pressing on it doesn't do a thing.

**Comment by dimkonomis** [comment]
Issues have been resolved in Version 1.0.3

**Comment by aripuzo** [comment]
Still have this problem
